package com.dendnight.core.domain;

import java.util.Date;

public class AccessLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.user_id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.ip
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.device
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String device;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.browser
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String browser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.os
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String os;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column access_log.details
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String details;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.id
     *
     * @return the value of access_log.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.id
     *
     * @param id the value for access_log.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.user_id
     *
     * @return the value of access_log.user_id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.user_id
     *
     * @param userId the value for access_log.user_id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.ip
     *
     * @return the value of access_log.ip
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.ip
     *
     * @param ip the value for access_log.ip
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.device
     *
     * @return the value of access_log.device
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getDevice() {
        return device;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.device
     *
     * @param device the value for access_log.device
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setDevice(String device) {
        this.device = device == null ? null : device.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.time
     *
     * @return the value of access_log.time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.time
     *
     * @param time the value for access_log.time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.browser
     *
     * @return the value of access_log.browser
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getBrowser() {
        return browser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.browser
     *
     * @param browser the value for access_log.browser
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setBrowser(String browser) {
        this.browser = browser == null ? null : browser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.os
     *
     * @return the value of access_log.os
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getOs() {
        return os;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.os
     *
     * @param os the value for access_log.os
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setOs(String os) {
        this.os = os == null ? null : os.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column access_log.details
     *
     * @return the value of access_log.details
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column access_log.details
     *
     * @param details the value for access_log.details
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }
}