package com.dendnight.core.domain;

import java.util.Date;

public class AccountInf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.user_id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.username
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.password
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.user_type
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.count
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_inf.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.user_id
     *
     * @return the value of account_inf.user_id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.user_id
     *
     * @param userId the value for account_inf.user_id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.username
     *
     * @return the value of account_inf.username
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.username
     *
     * @param username the value for account_inf.username
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.password
     *
     * @return the value of account_inf.password
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.password
     *
     * @param password the value for account_inf.password
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.user_type
     *
     * @return the value of account_inf.user_type
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.user_type
     *
     * @param userType the value for account_inf.user_type
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.count
     *
     * @return the value of account_inf.count
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.count
     *
     * @param count the value for account_inf.count
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.created_time
     *
     * @return the value of account_inf.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.created_time
     *
     * @param createdTime the value for account_inf.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.created_by
     *
     * @return the value of account_inf.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.created_by
     *
     * @param createdBy the value for account_inf.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.updated_time
     *
     * @return the value of account_inf.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.updated_time
     *
     * @param updatedTime the value for account_inf.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.updated_by
     *
     * @return the value of account_inf.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.updated_by
     *
     * @param updatedBy the value for account_inf.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.deleted
     *
     * @return the value of account_inf.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.deleted
     *
     * @param deleted the value for account_inf.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_inf.version
     *
     * @return the value of account_inf.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_inf.version
     *
     * @param version the value for account_inf.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}