package com.dendnight.core.domain;

import java.util.Date;

public class FileInf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_inf.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_inf.type
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_inf.size
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_inf.name
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_inf.path
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_inf.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_inf.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_inf.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_inf.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_inf.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_inf.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_inf.id
     *
     * @return the value of file_inf.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_inf.id
     *
     * @param id the value for file_inf.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_inf.type
     *
     * @return the value of file_inf.type
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_inf.type
     *
     * @param type the value for file_inf.type
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_inf.size
     *
     * @return the value of file_inf.size
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_inf.size
     *
     * @param size the value for file_inf.size
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_inf.name
     *
     * @return the value of file_inf.name
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_inf.name
     *
     * @param name the value for file_inf.name
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_inf.path
     *
     * @return the value of file_inf.path
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_inf.path
     *
     * @param path the value for file_inf.path
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_inf.created_time
     *
     * @return the value of file_inf.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_inf.created_time
     *
     * @param createdTime the value for file_inf.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_inf.created_by
     *
     * @return the value of file_inf.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_inf.created_by
     *
     * @param createdBy the value for file_inf.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_inf.updated_time
     *
     * @return the value of file_inf.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_inf.updated_time
     *
     * @param updatedTime the value for file_inf.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_inf.updated_by
     *
     * @return the value of file_inf.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_inf.updated_by
     *
     * @param updatedBy the value for file_inf.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_inf.deleted
     *
     * @return the value of file_inf.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_inf.deleted
     *
     * @param deleted the value for file_inf.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file_inf.version
     *
     * @return the value of file_inf.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file_inf.version
     *
     * @param version the value for file_inf.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}