package com.dendnight.core.domain;

import java.util.Date;

public class ImageInf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.height
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.width
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer width;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.longitude
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.latitude
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.readme
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String readme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.camera_model
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String cameraModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.camera_brand
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String cameraBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.lens_brand
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String lensBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.date_taken
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Date dateTaken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.lens_model
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String lensModel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.program_name
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String programName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image_inf.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.id
     *
     * @return the value of image_inf.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.id
     *
     * @param id the value for image_inf.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.height
     *
     * @return the value of image_inf.height
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.height
     *
     * @param height the value for image_inf.height
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.width
     *
     * @return the value of image_inf.width
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getWidth() {
        return width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.width
     *
     * @param width the value for image_inf.width
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.longitude
     *
     * @return the value of image_inf.longitude
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.longitude
     *
     * @param longitude the value for image_inf.longitude
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.latitude
     *
     * @return the value of image_inf.latitude
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.latitude
     *
     * @param latitude the value for image_inf.latitude
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.readme
     *
     * @return the value of image_inf.readme
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getReadme() {
        return readme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.readme
     *
     * @param readme the value for image_inf.readme
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setReadme(String readme) {
        this.readme = readme == null ? null : readme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.camera_model
     *
     * @return the value of image_inf.camera_model
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getCameraModel() {
        return cameraModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.camera_model
     *
     * @param cameraModel the value for image_inf.camera_model
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCameraModel(String cameraModel) {
        this.cameraModel = cameraModel == null ? null : cameraModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.camera_brand
     *
     * @return the value of image_inf.camera_brand
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getCameraBrand() {
        return cameraBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.camera_brand
     *
     * @param cameraBrand the value for image_inf.camera_brand
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCameraBrand(String cameraBrand) {
        this.cameraBrand = cameraBrand == null ? null : cameraBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.lens_brand
     *
     * @return the value of image_inf.lens_brand
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getLensBrand() {
        return lensBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.lens_brand
     *
     * @param lensBrand the value for image_inf.lens_brand
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setLensBrand(String lensBrand) {
        this.lensBrand = lensBrand == null ? null : lensBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.date_taken
     *
     * @return the value of image_inf.date_taken
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Date getDateTaken() {
        return dateTaken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.date_taken
     *
     * @param dateTaken the value for image_inf.date_taken
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setDateTaken(Date dateTaken) {
        this.dateTaken = dateTaken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.lens_model
     *
     * @return the value of image_inf.lens_model
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getLensModel() {
        return lensModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.lens_model
     *
     * @param lensModel the value for image_inf.lens_model
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setLensModel(String lensModel) {
        this.lensModel = lensModel == null ? null : lensModel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.program_name
     *
     * @return the value of image_inf.program_name
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getProgramName() {
        return programName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.program_name
     *
     * @param programName the value for image_inf.program_name
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setProgramName(String programName) {
        this.programName = programName == null ? null : programName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.created_time
     *
     * @return the value of image_inf.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.created_time
     *
     * @param createdTime the value for image_inf.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.created_by
     *
     * @return the value of image_inf.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.created_by
     *
     * @param createdBy the value for image_inf.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.updated_time
     *
     * @return the value of image_inf.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.updated_time
     *
     * @param updatedTime the value for image_inf.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.updated_by
     *
     * @return the value of image_inf.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.updated_by
     *
     * @param updatedBy the value for image_inf.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.deleted
     *
     * @return the value of image_inf.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.deleted
     *
     * @param deleted the value for image_inf.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image_inf.version
     *
     * @return the value of image_inf.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image_inf.version
     *
     * @param version the value for image_inf.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}