package com.dendnight.core.domain;

import java.util.Date;

public class ParamSys {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_sys.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_sys.name
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_sys.code
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_sys.value
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_sys.readme
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String readme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_sys.relation
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer relation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_sys.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_sys.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_sys.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_sys.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_sys.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column param_sys.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_sys.id
     *
     * @return the value of param_sys.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_sys.id
     *
     * @param id the value for param_sys.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_sys.name
     *
     * @return the value of param_sys.name
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_sys.name
     *
     * @param name the value for param_sys.name
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_sys.code
     *
     * @return the value of param_sys.code
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_sys.code
     *
     * @param code the value for param_sys.code
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_sys.value
     *
     * @return the value of param_sys.value
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_sys.value
     *
     * @param value the value for param_sys.value
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_sys.readme
     *
     * @return the value of param_sys.readme
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getReadme() {
        return readme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_sys.readme
     *
     * @param readme the value for param_sys.readme
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setReadme(String readme) {
        this.readme = readme == null ? null : readme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_sys.relation
     *
     * @return the value of param_sys.relation
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_sys.relation
     *
     * @param relation the value for param_sys.relation
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setRelation(Integer relation) {
        this.relation = relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_sys.created_time
     *
     * @return the value of param_sys.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_sys.created_time
     *
     * @param createdTime the value for param_sys.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_sys.created_by
     *
     * @return the value of param_sys.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_sys.created_by
     *
     * @param createdBy the value for param_sys.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_sys.updated_time
     *
     * @return the value of param_sys.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_sys.updated_time
     *
     * @param updatedTime the value for param_sys.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_sys.updated_by
     *
     * @return the value of param_sys.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_sys.updated_by
     *
     * @param updatedBy the value for param_sys.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_sys.deleted
     *
     * @return the value of param_sys.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_sys.deleted
     *
     * @param deleted the value for param_sys.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column param_sys.version
     *
     * @return the value of param_sys.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column param_sys.version
     *
     * @param version the value for param_sys.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}