package com.dendnight.core.domain;

import java.util.Date;

public class UserInf {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.name
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.email
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.mobile
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.age
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.gender
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.birthday
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.readme
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private String readme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Date updatedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Byte deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_inf.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.id
     *
     * @return the value of user_inf.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.id
     *
     * @param id the value for user_inf.id
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.name
     *
     * @return the value of user_inf.name
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.name
     *
     * @param name the value for user_inf.name
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.email
     *
     * @return the value of user_inf.email
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.email
     *
     * @param email the value for user_inf.email
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.mobile
     *
     * @return the value of user_inf.mobile
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.mobile
     *
     * @param mobile the value for user_inf.mobile
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.age
     *
     * @return the value of user_inf.age
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.age
     *
     * @param age the value for user_inf.age
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.gender
     *
     * @return the value of user_inf.gender
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.gender
     *
     * @param gender the value for user_inf.gender
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.birthday
     *
     * @return the value of user_inf.birthday
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.birthday
     *
     * @param birthday the value for user_inf.birthday
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.readme
     *
     * @return the value of user_inf.readme
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public String getReadme() {
        return readme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.readme
     *
     * @param readme the value for user_inf.readme
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setReadme(String readme) {
        this.readme = readme == null ? null : readme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.created_time
     *
     * @return the value of user_inf.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.created_time
     *
     * @param createdTime the value for user_inf.created_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.created_by
     *
     * @return the value of user_inf.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.created_by
     *
     * @param createdBy the value for user_inf.created_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.updated_time
     *
     * @return the value of user_inf.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.updated_time
     *
     * @param updatedTime the value for user_inf.updated_time
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.updated_by
     *
     * @return the value of user_inf.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.updated_by
     *
     * @param updatedBy the value for user_inf.updated_by
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.deleted
     *
     * @return the value of user_inf.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Byte getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.deleted
     *
     * @param deleted the value for user_inf.deleted
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setDeleted(Byte deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_inf.version
     *
     * @return the value of user_inf.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_inf.version
     *
     * @param version the value for user_inf.version
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}