package com.dendnight.core.mapper;

import com.dendnight.core.domain.AccountInf;

public interface AccountInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int insert(AccountInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int insertSelective(AccountInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    AccountInf selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int updateByPrimaryKeySelective(AccountInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int updateByPrimaryKey(AccountInf record);
}