package com.dendnight.core.mapper;

import com.dendnight.core.domain.ImageInf;

public interface ImageInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int insert(ImageInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int insertSelective(ImageInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    ImageInf selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int updateByPrimaryKeySelective(ImageInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int updateByPrimaryKey(ImageInf record);
}