package com.dendnight.core.mapper;

import com.dendnight.core.domain.ParamSys;

public interface ParamSysMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_sys
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_sys
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int insert(ParamSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_sys
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int insertSelective(ParamSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_sys
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    ParamSys selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_sys
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int updateByPrimaryKeySelective(ParamSys record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table param_sys
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int updateByPrimaryKey(ParamSys record);
}