package com.dendnight.core.mapper;

import com.dendnight.core.domain.UserInf;

public interface UserInfMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int insert(UserInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int insertSelective(UserInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    UserInf selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int updateByPrimaryKeySelective(UserInf record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_inf
     *
     * @mbggenerated Sun Apr 06 17:47:23 CST 2014
     */
    int updateByPrimaryKey(UserInf record);
}